<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
	  <EnableReleaseTracking>false</EnableReleaseTracking>
	  <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn);RS2000</NoWarn>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\..\..\CSharpPractice\CSharpPracticeSolution\CSharpPracticeLibrary\Helpers\LoopHelpers.cs" Link="Helpers\LoopHelpers.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
</Project>
